config/routes.rb
LearnRails::Application.routes.draw do




  resources :contacts, only: [:new, :create]
  resources :visitors, only: [:new, :create]
  root to: 'visitors#new'



end

app/models/contact.rb
class Contact < ActiveRecord::Base
  has_no_table

  column :name, :string
  column :email, :string
  column :content, :string

  validates_presence_of :name
  validates_presence_of :email
  validates_presence_of :content
  validates_format_of :email, :with => /\A[-a-z0-9_+\.]+\@([-a-z0-9]+\.)+[a-z0-9]{2,4}\z/i
  validates_length_of :content, :maximum => 500

  def update_spreadsheet
    connection = GoogleDrive.login(ENV["GMAIL_USERNAME"], ENV["GMAIL_PASSWORD"])
    ss = connection.spreadsheet_by_title('Learn-Rails-Example')
    if ss.nil?
      ss = connection.create_spreadsheet('Learn-Rails-Example')
    end
    ws = ss.worksheets[0]
    last_row = 1 + ws.num_rows
    ws[last_row, 1] = Time.new
    ws[last_row, 2] = self.name
    ws[last_row, 3] = self.email
    ws[last_row, 4] = self.content
    ws.save
  end

end

app/models/visitor.rb
class Visitor < ActiveRecord::Base
  has_no_table
  column :email, :string
  validates_presence_of :email
  validates_format_of :email, :with => /\A[-a-z0-9_+\.]+\@([-a-z0-9]+\.)+[a-z0-9]{2,4}\z/i


  def subscribe_to_mailchimp testing=false
    return true if (Rails.env.test? && !testing)
    list_id = ENV['MAILCHIMP_LIST_ID']

    response = Rails.configuration.mailchimp.lists.subscribe({
                                                                 id: list_id,
                                                                 email: {email: email},
                                                                 double_optin: false,
                                                             })
    response
  end



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(secure_params)
    if @contact.valid?
      @contact.update_spreadsheet
      UserMailer.contact_email(@contact).deliver
      flash[:notice] = "Message sent from #{@contact.name}."
      redirect_to root_path
    else
      render :new
    end
  end

  private

  def secure_params
    params.require(:contact).permit(:name, :email, :content)
  end

end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController



  def new
    @visitor = Visitor.new
  end

  def create
    @visitor = Visitor.new(secure_params)
    if @visitor.valid?
      @visitor.subscribe_to_mailchimp
      flash[:notice] = "Signed up #{@visitor.email}."
      redirect_to root_path
    else
      render :new
    end
  end

  private

  def secure_params
    params.require(:visitor).permit(:email)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/contacts/new.html.erb
<% content_for :title do %>Contact<% end %>
<h3>Contact</h3>
<div class="form">
  <%= simple_form_for @contact do |form| %>
    <%= form.error_notification %>
    <%= form.input :name, autofocus: true %>
    <%= form.input :email %>
    <%= form.input :content, as: :text %>
    <%= form.button :submit, 'Submit', class: 'submit' %>
  <% end %>
</div>

app/views/gemutiles/about.html.erb
<%= content_for :page_title, 'GemUtiles' %>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Zurb Foundation %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div data-alert class="alert-box round <%= name == :notice ? "success" : "alert" %>">
      <%= content_tag :div, msg %>
      <a href="#" class="close">&times;</a>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Zurb Foundation 4 %>
<nav class="top-bar">
  <ul class="title-area">
    <li class="name"><%= link_to 'PWL', root_path %></li>

    <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
  </ul>
  <div class="top-bar-section">
    <ul>
      <%= render 'layouts/navigation_links' %>
    </ul>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<li><%= link_to 'à propos', page_path('about') %></li>
<li><%= link_to 'Contact', new_contact_path('contact') %></li>
<li><%= link_to 'Historique', page_path('historique') %></li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Learn Rails" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Learn Rails" %>">
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
    <%# Modernizr is required for Zurb Foundation %>
    <%= javascript_include_tag "vendor/custom.modernizr" %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>

app/views/pages/about.html.erb
<% content_for :title do %>Projet Web Love
<% end %>
<div class="column12">
  <h1>Pour que la technologie disparaisse au profit de l'usage.</h1>

  <p>

    Etude de faisabilité sur la fabrication d'un logiciel open source d'édition de base de données ET de publication
    web, basé sur une rétro-ingénierie du Logiciel Apple FileMaker Pro (fonctionnement en réseau, simplicité, graphisme,
    multi-langue, etc.), prenant en compte les besoins actuels de publications sur différents supports (intégration
    d'Apache Cordova).

  <
    <ul>
      <li>libre</li>
      <li>européen</li>
      <li>multilingue de part sa création, sa documentation</li>
      <li>Mise en place d'une certification européenne</li>
    </ul>
  
  <h3>Ce programme doit permettre à chacun et de façon évidente:</h3>
    <ul>
      <li>de traiter des données (Créer, Lire, Mettre à jour, Détruire, Chercher, Trier, Calculer)
      </li>
      <li>d’utiliser un outil graphique pour la mise en page des données,</li>
      <li>de présenter et de publier sur le web des données (texte, chiffres, images, vidéos, musiques) de façon
        extrêmement simple
      </li>
      <li>de savoir de façon sure où sont ses données.</li>
    </ul>
  
  <p>
    De nombreuses fois, je me suis dit... “Mais c’est pas vrais... Il n’y a personne qui vas proposer la même chose que
    FileMaker mais à destination du web et sous Ubuntu…” Et oui… Il n'existe aucun logiciel similaire à FileMakerPro
    sous Ubuntu, pourtant le monde libre en a besoin... Visiblement c’est compliqué de faire simple ou alors il y a
    quelque chose de pourris au Royaume du Danemark…
</p>
  <p>
    Aujourd'hui, un utilisateur lambda, un néophyte à donc l'obligation d'utiliser un ensemble de technologies multiples
    et complexes.
</p>
  <p>
  <ul>
    <li>PHP avec sql avec ou sans framework (Laravelle,...) +++</li>
    <li> Ruby + postgres + rails + javascript + botstrapp++++</li>
    <li>Java …</li>
  </ul>
  <p>
    Le temps d'apprentissage et de vague maîtrise d'au moins une de ces solutions (pour la majorité des néophytes) est
    au
    minimum d'un an... </p>
  <h2>Solutions existantes</h2>
  <ul>
    <li> Il y a OfficeBase... moche et ne fonctionne pas en réseau naturellement et ne publie pas sur le web...</li>
    <li>Il y a kexi http://www.calligra.org/kexi/ qui ressemble à Acces par sa laideur et son approche.</li>
    <li> http://www.wavemaker.com --> Tourne sur Java --> C'est ce qui se rapproche le plus de ce qu'il faut proposer.
      Racheté
      à VMWare il y a deux ans. Il appartient maintenant à une société indienne. Le code source est sur github.
      https://github.com/cloudjee/wavemaker mais, Il ne fonctionne pas avec le jdk libre.
    </li>
  </ul>

  <h2>Avantages et éléments différenciateurs</h2>
  <ul>
  <li>L’interface graphique</li>
  <li>Le minimum de ligne de code</li>
  <li>Le maximum de web</li>
  <li>Un outil résolument européen et multilingue de part sa création, sa documentation, sa traduction.</li>
  <li>Un outil sur et fiable dans le temps.</li>
  </ul>

  <h2>Qui pourrait appuyer le projet WebLove en France ?</h2>

    <ul>
  <li>Audrey Harris PDG de Soubis</li>
  <li>    Benoît Thieulin Directeur général de l'agence digitale la Netscouade Président du CNNum </li>
<li>    Brigitte Vallée Directrice de Recherche au CNRS </li>
<li>    Christine Balagué Vice-présidente du CNNum  </li>
<li>    Cyril Garcia Directeur de la stratégie Cap Gemini </li>
<li>    Daniel Kaplan Délégué Général de la Fing  </li>
<li>    Michel Briand Directeur adjoint de la formation à Télécom Bretagne/Vice-président Brest Métropole </li>
<li>    Nathalie Andrieux Directrice du numérique du groupe La Poste  </li>
<li>    Serge Abiteboul Directeur de Recherche à l'INRIA  </li>
<li>    Sophie Pène Professeur à l'Université Paris Descarte  </li>
<li>    Valérie Peugeot Chercheuse à Orange Lab, Présidente de Vécam, Vice-présidente du CNNum  </li>
<li>    des écoles informatiques  </li>
<li>    des universitaires  </li>
<li>    des chercheurs  </li>
<li>    La Région Île de France </li>
<li>    La Ville de Paris </li>
<li>    Le Grand Paris  </li>
<li>    Les agglomérations  </li>
<li>    Les départements  </li>
<li>    Le ministère de l'Economie Numérique  </li>
<li>    Stéphane Distinguin </li>
<li>    Antoine Torikian  </li>
<li>    Epitec  </li>
<li>    Epita </li>
<li>    Etic  </li>
<li>  42  </li>
<li>    Simplon </li>
<li>    Telecom Paris Tech  </li>
<li>Mine Telecom...</li>
    </ul>
<p>  En fonction du résultat de cette étude, Il faudra travailler sur une demande subvention européenne liée à la
  réalisation. Budget estimé de la demande de subvention : 2 million d’euros
</p>
  <h2>WebLove avec qui en Europe ?</h2>
  <p>

  Il faudra mettre en place les relations nécessaires dans chacun des pays européens.
</p>
<ul>
<li>République fédérale d'Allemagne</li>
  <li>République d'Autriche</li>
  <li>Royaume de Belgique</li>
  <li>République de Bulgarie</li>
  <li>République de Chypre</li>
  <li>République de Croatie</li>
  <li>Royaume du Danemark</li>
  <li>Royaume d'Espagne</li>
  <li>République d'Estonie</li>
  <li>République de Finlande</li>
  <li>République française</li>
  <li>République hellénique</li>
  <li>Hongrie Irlande</li>
  <li>République Italienne</li>
  <li>République de Lettonie</li>
  <li>République de Lituanie</li>
  <li>Grand-Duché de Luxembourg</li>
  <li>République de Malte</li>
  <li>Royaume des Pays-Bas</li>
  <li>République de Pologne</li>
  <li>République portugaise</li>
  <li>République tchèque</li>
  <li>Roumanie</li>
  <li>Royaume-Uni</li>
  <li>République slovaque</li>
  <li>République de Slovénie</li>
  <li>République fédérale d'Allemagne</li>
  <li>République d'Autriche</li>
  <li>Royaume de Belgique</li>
  <li>République de Bulgarie</li>
  <li>République de Chypre</li>
  <li>République de Croatie</li>
  <li>Royaume du Danemark</li>
  <li>Royaume d'Espagne</li>
  <li>République d'Estonie</li>
  <li>République de Finlande</li>
  <li>République française</li>
  <li>République hellénique</li>
  <li>Hongrie Irlande</li>
  <li>République Italienne</li>
  <li>République de Lettonie</li>
  <li>République de Lituanie</li>
  <li>Grand-Duché de Luxembourg</li>
  <li>République de Malte</li>
  <li>Royaume des Pays-Bas</li>
  <li>République de Pologne</li>
  <li>République portugaise</li>
  <li>République tchèque</li>
  <li>Roumanie</li>
  <li>Royaume-Uni</li>
  <li>République slovaque</li>
  <li>République de Slovénie</li>
</ul>

  <h2>WebLove, c'est possible !!! Le monde en a besoin.</h2>
<ul>
  <li>Au moins 5 développeurs pointus par pays.</li>
  <li>40 vrais développeurs.</li>
  <li>Une bonne organisation.</li>
  <li>Une très bonne analyse en amont…</li>
  <li>Un budget !</li>
</ul>

<h2>On récapitule.</h2>
<p>C’est un projet de dossier de demande de subvention pour réaliser une étude de faisabilité pour un logiciel open
  source.
<p>L’objectif de ce logiciel est de proposer la fabrication d'un logiciel libre d'édition de base de données ET de
  publication web, basé sur une retro-ingenerie du Logiciel Apple FileMaker Pro (fonctionnement en réseau, simplicité,
  graphisme, multi-langue, etc.), prenant en compte les besoins actuels de publications sur différents supports
  (intégration d'Apache Cordova).
</div>

app/views/pages/contact.html.erb
<% content_for :title do %>Contact<%end%>
<h3>Contact</h3>
<div class="form">
  <%= simple_form_for :contact, url: contact_path do |form| %>
    <%= form.input :name, autofocus: true %>
    <%= form.input :email %>
    <%= form.input :content, as: :text %>
    <%= form.button :submit, 'Submit', class: 'submit' %>
  <% end %>
</div>

app/views/pages/historique.html.erb
<h1>Date : le 22/12/2013</h1>
<h2>Objet : Résumé des épisodes précédents... (à savoir depuis le 28 octobre 2013 --> )</h2>
<h3>Appréhension de différents blocs d'information :</h3>

Décision d'installer Archlinux sur mon PC à la maison - Un processeur  Atlon 64 avec 2 Mo de ram et une carte vidéo Amd


Installation d'Archlinux --> qui ne fonctionne pas avec une carte vidéo "Amd" malgré l'installation du driver propriétaire...

      Cela se remarque quand on lance startx --> on obtient un joli plantage

(petite plaisanterie qui m'a pris 72 heures au moins - installation, réinstallation...)

Après une semaine d'ébats inassouvis  --> jetage d'Archlinux

Installation de Ubuntu --> trops lourd sur mon PC et sur les portables de Simplon(Lenovo T60 - Bonne machine quand même, mais visiblement problème avec le carte wifi et unix / non fonctionnement sur Archlinux ni sur Ubuntu).

Après une semaine d'ébats inassouvis --> jetage de Ubuntu

Installation de Lubuntu --> Version plus légère  de Ubuntu et vraiment agréable à utiliser sur les machine peu récentes.

    Présentation de Tweeter Bootstrap et de Foundation
    Présentation de SublimeText2
    Présentation de Sinatra...
    Présentation de Ruby
    Présentation de rails

 --> Tutoriel trop lourd en première approche de Michel Heart

 Je cherche des trucs, je tombe sur wavemaker
-->

Découverte de  Bloggers de ... plus léger... mais bon ... avec Ruby 1.9.3, évidemment on est en version 2 donc quelques soucis ...

Phases de doute, mais il semble que tout le monde soit un peu perdu et dans le même cas que moi.

J'essaye de savoir  par quel bout prendre dans la masse d'informations reçues

15 jours de coupure...

1 semaine d'aération de cerveaux
  Lieux : à la montagne avec un très très très ... bas débit asdl
  Machine : un pc avec windows 8
  Tentative : Installer ruby et rails --> on va dire bof....
  Décision : installer une machine virtuelle --> ça le fait --> une journée de téléchargement
  Récupération de Lubuntu --> une journée de téléchargement
  Installation de Ubuntu dans la machine virtuelle --> ça le fait
  Téléchargement de Rvm, Ruby, installation des gems, téléchargement de SublimeText
  Prêt pour bosser, yes...
  Ah ben non ça marche pas... On ne sait pas pourquoi node Js n'est pas installé par défaut.

Je suis un peu contrarié... Je me dit que franchement #{|[{`[|`é\"\'(`^-|`^è^[_ç é&r_&réèà é&é_" et là je reste poli...

Bon je rentre... j'ai un peu le sentiment de comment dire ...

  Je cherche des trucs...
    Je tombe sur servoy : ça a  l'air interressant mais ça ne fonctionne pas avec le jdk libre --> don je le supprime de ma machine et installe le java d'oracle... Encore un grand moment...

Après 36 h et une réussite à l'installation, j'en ai tellement chier que je ne sais même plus pourquoi je l'ai installé...

Bon allez un autre tuto

app/views/visitors/new.html.erb
<% content_for :title do %>webloveand.co<% end %>
<% content_for :description do %>Website d'André Baudin-Laurencin<% end %>

<div class="column12">
<section>
      <img src="http://lorempixel.com/1170/600/cats/2" alt="image de chat">

   <h1>Pour rester en contact... </h1>


      <%= simple_form_for @visitor do |f| %>
        <%= f.error_notification %>
        <%= f.input :email, label: false, :placeholder => 'Votre adresse mail...' %>
        <%= f.button :submit, "Pour recevoir la news letter", :class => "submit" %>
      <% end %>

</section>
</div>